name: ChangeSkinUI
main: CSkinUI\Main
api: 5.0.0
version: 1.2.0
authors: [RassPocket, GamerMJay, GLX20]
description: A PocketMine-MP Skin Plugin



permissions:
 cskinui.use:
  default: op
  description: "Open the ChangeSkinUI menu"
