name: EasySkin
main: GamerMJay\EasySkin\Main
api: 4.0.0
version: 1.1.0
authors: [GamerMJay, GLX20]
description: A PocketMine-MP Skin Plugin



permissions:
 easyskin.use:
  default: op
  description: "Open the EasySkin menu"
